Name:           ros-melodic-catkin-pip
Version:        0.2.3
Release:        1%{?dist}
Summary:        ROS catkin_pip package

Group:          Development/Libraries
License:        BSD
URL:            http://github.com/asmodehn/catkin_pip
Source0:        %{name}-%{version}.tar.gz

Requires:       python-devel >= 2.7.5
Requires:       python-pip >= 1.5.4
BuildRequires:  git >= 1.9.1
BuildRequires:  python-devel >= 2.7.5
BuildRequires:  python-pip >= 1.5.4
BuildRequires:  ros-melodic-catkin

%description
Catkin macros to allow using pure python packages in usual catkin workspaces
with normal python workflow.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Jun 15 2019 AlexV <asmodehn@gmail.com> - 0.2.3-1
- Autogenerated by Bloom

